
---
- hosts: webhosts
  remote_user: netris
  become: yes
  gather_facts: no
  vars_files:
  - roles/common/vars/main.yml
  vars:
    app_name: wordpress
  pre_tasks:
  - set_fact:
      ansible_distribution_major_version: "7"
  roles:
  - common
  - docker-app-backup
