---
- name: Check if rclone exists
  stat:
    path: "{{ rclone_path }}"
  register: rclone
  
- name: Download rclone install script
  command: "cd {{ script_root }} && curl -O https://rclone.org/install.sh"
  when: rclone.stat.exists == False
  
- name: Change permission on rclone install script
  file:
    path: "{{ script_root }}/install.sh"
    mode: 0755
  when: rclone.stat.exists == False
    
- name: Install rclone
  script: "{{ script_root }}/install.sh"
  when: rclone.stat.exists == False
    
- name: Delete rclone install script
  file:
    path: "{{ script_root }}/install.sh"
    state: absent
  when: rclone.stat.exists == False
  
- name: create backup dir
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
  - { path: '{{ backup_dir }}', state: 'directory' }
  
- name: Copy template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { src: 'backup.sh.j2', dest: '{{ script_root }}/{{ app_name }}-backup.sh', mode: '0700' }
  - { src: 'hosts.txt.j2', dest: '{{ backup_dir }}/{{ app_name }}-hosts.txt' }
  - { src: 'rclone.conf.j2', dest: '{{ rclone_config_dir }}/rclone.conf', mode: '0600' }
  
- name: Schedule backups
  cron:
    name: "{{ item.name }}"
    minute: "0"
    hour: "{{ item.time }}"
    job: "{{ item.job }}"
    state: present
  with_items:
  - { name: '{{ app_name }}-backup', time: '1', job: '{{ script_root }/{{ app_name }}-backup.sh' }
  - { name: 'cloud sync', time: '4', job: 'rclone sync {{ backup_dir }} encrypt:' }
