---
- name: Create Script Directory
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
  - { path: '{{ script_root }}', state: 'directory' }

- name: Check if rclone Exists
  stat:
    path: "{{ rclone_path }}"
  register: rclone
  
- name: Download rclone Install Script
  command: "cd {{ script_root }} && curl -O {{ rclone_url }}"
  when: rclone.stat.exists == False
  
- name: Change Permission on rclone Install Script
  file:
    path: "{{ script_root }}/install.sh"
    mode: 0755
  when: rclone.stat.exists == False
    
- name: Install rclone
  script: "{{ script_root }}/install.sh"
  when: rclone.stat.exists == False
    
- name: Delete rclone Install Script
  file:
    path: "{{ script_root }}/install.sh"
    state: absent
  when: rclone.stat.exists == False
  
- name: Create Backup Directory
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
  - { path: '{{ backup_dir }}', state: 'directory' }
  
- name: Copy Templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
  - { src: 'rclone.conf.j2', dest: '{{ rclone_config_dir }}/rclone.conf', mode: '0660' }
  - { src: '{{ app_name }}-backup.sh.j2', dest: '{{ script_root }}/{{ app_name }}-backup.sh', mode: '0740' }
  
- name: Schedule Backup
  cron:
    name: "{{ item.name }}"
    minute: "0"
    hour: "{{ item.time }}"
    job: "{{ item.job }}"
    state: present
  loop:
  - { name: '{{ app_name }}-backup', time: '8', job: '{{ script_root }}/{{ app_name }}-backup.sh > /dev/null 2>&1' }
  - { name: 'cloud sync', time: '12', job: 'rclone sync {{ backup_dir }} encrypt: --transfers 1 --buffer-size 8M > /dev/null 2>&1' }
  when: app_name != "docker"

- name: Schedule Backup
  cron:
    name: "{{ item.name }}"
    minute: "0"
    hour: "{{ item.time }}"
    day: "{{ item.day }}"
    job: "{{ item.job }}"
    state: present
  loop:
  - { name: '{{ app_name }}-backup', time: '10', day: '12', job: '{{ script_root }}/{{ app_name }}-backup.sh > /dev/null 2>&1' }
  when: app_name == "docker"
